### ISSUE TITLE
Fix command only trying to fix one block

### ISSUE THREAD

**Issue by lamarios** [trapexit/bbf#13]
I have a not very healthy disk with a lot of bad blocks (22616) but when i run the fix command it only seems to be fixing the first block of my bad block file:

```
sudo bbf -i 3t.WMC4N0J3YP10 -c my-captcha  fix  /dev/sdc
Reading block 5694484064 succeeded (1 attempts)
Writing block 5694484064 succeeded (1 attempts)
```

and then it mounts the drive. Is it expected behavior ?

**Comment by trapexit** [comment]
Sounds like something is automatically mounting the device. bbf is definitely not doing that. Try removing it from fstab and trying again.

**Comment by trapexit** [comment]
What distro? Is it mounting to /media/${USER}/ ? If so then it could be the desktop's filemanager trying to mount it. Might reset when bbf is trying to write to it and it sees it again. Would need to turn that off (or wipe the beginning of the drive so

**Comment by lamarios** [comment]
Using Arch as a server without much installed on it so there are no desktop
environment.

 It is mounted in the /mnt folder. The interesting part is that it mounts
it back at the proper mount point even if the fstab entre is commented.

**Comment by trapexit** [comment]
https://dominicm.com/mount-filesystem-partitions-in-arch-linux/

via systemd maybe?

**Comment by lamarios** [comment]
I’ll check that out on my side as it seems that it’s not related to bbf.
Thanks !

**Comment by lamarios** [comment]
Well, I edited the fstab and rebooted to make sure and when i run the bbf command it will stop at the same state as before but the disk won't be automatically mounted this time.

**Comment by trapexit** [comment]
No, bbf works with the block device. It doesn't care at all.

What do you mean it stops? It exits? How did you create the block list? Does scanning work?

**Comment by lamarios** [comment]
The only output I get from the fix command is what I posted originally it
runs on the first block of my bad block file then stops, no error
whatsoever.

The scan command works, that’s how I got the bad block file.

**Comment by trapexit** [comment]
It's a bug. Fix incoming.

**Comment by trapexit** [comment]
Grab the latest. Should work. Sorry about that. Clearly didn't test it after changing things last time.

**Comment by lamarios** [comment]
Works great, thanks !
