### ISSUE TITLE
burnin left my disk filled with FF. 

### ISSUE THREAD

**Issue by bvwelch** [trapexit/bbf#30]
I thought it would be non-destructive?  Ubuntu 22.04 lts.  latest bbf from this repo.

**Comment by trapexit** [comment]
Really sorry. Seems like a refactor a while ago inadvertently changed the behavior. 

I'll patch it asap.

**Comment by bvwelch** [comment]
I should have been more careful. On the bright side, now I dont have to study mergerfs anymore. ;-)

**Comment by trapexit** [comment]
:-/ Again, sorry about that. Not sure how I missed that.

**Comment by trapexit** [comment]
> I dont have to study mergerfs anymore.

How were you using bbf with mergerfs?

**Comment by trapexit** [comment]
#31
